[package]
name       = "omaghy-tui"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
omaghy-model.workspace = true
omaghy-store.workspace = true
ratatui.workspace      = true
crossterm.workspace    = true
tui-input.workspace    = true
unicode-width.workspace = true
async-trait.workspace   = true
futures-util.workspace  = true
time.workspace         = true
tokio.workspace        = true
tracing.workspace      = true

[dev-dependencies]
insta.workspace = true
